services:
  mt5:
    build: .
    image: gmag11/metatrader5_vnc
    container_name: mt5
    # volumes:
    #   - ./config:/config
    ports:
      - 3000:3000
      - 8001:8001
      - 5000:5000 # unused port
      - 6000:6000 # unused port
    # env_file:
    #   - .env
